### PR TITLE
Added ability to use virtual scroll with different heights of elements

### PR DESCRIPTION
**Pull request by kykint**
Now virtual-scroll is working perfectly with dynamic-height elements. Also it works fine if elements could change their heights

### CODE REVIEW

**Comment by kykint** [comment]
Now virtual-scroll is working perfectly with dynamic-height elements. Also it works fine if elements could change their heights

**Comment by ourarash** [comment]
@kykint can you please post an example when the heights are different? For me when the height is variable, the scroll is very jerky.

**Comment by kykint** [comment]
@ourarash fixed in my branch. 
@rintoj Could you merge it to master? This version is working fine in real product

**Comment by twjacobsen** [comment]
Should this work with a multi-column setup? It dont seem to work for me when each item is 50% width.

**Comment by kykint** [comment]
Yes more then 1 items per row is not working. Will try to fix it. It works good for 1 item per row now

**Comment by rintoj** [comment]
@kykint, scroll is not working fine for multi column or when the number of items in the array are changed. Can you please check?

screen shot 2018-01-25 at 8 14 59 pm

**Comment by kykint** [comment]
@rintoj I have almost fixed all issues, but didn't push yet. Will do it in several days

**Comment by kykint** [comment]
@rintoj I have updated virtual-scroll.ts

**Comment by kykint** [comment]
@rintoj Now it is fixed, could do check and merge?

**Comment by bolota** [comment]
Hello all and thx for this.

@kykint I have a little problem with the new updates. If i have items with different heights when i scroll the scrollbar-thumb is moving up and down.

**Comment by patcat** [comment]
@kykint I had a similar issue to the one mentioned above and had to move `previousStart` and `previousEnd` to get the end event firing. I moved them here:

```
...
 else {
  _this.change.emit({ start: start, end: end });
}
_this.previousStart = start;
 _this.previousEnd = end;
```

You'd mentioned you'd updated it on your branch at some point, so not sure if somehow that change got undone while putting together the latest commit for the pull request?

**Comment by kykint** [comment]
@patcat Fixed in branch

**Comment by bolota** [comment]
@kykint Hello, 

Can you make a demo?

thank you!

**Comment by mhumeniuk** [comment]
For me it at some point after loading additional items on end event the list gets items are not displayed

**Comment by lucasbasquerotto** [comment]
@kykint Could you make a fork of this repo while this feature is not yet merged?

**Comment by fredericojesus** [comment]
@kykint For me this is not working at all.
I have a feed page, think of something like facebook or twitter feed, item heights are always different.
I see a lot of flickering on items and on the scrollbar.

**Comment by mhumeniuk** [comment]
@fredericojesus Could you explain in more details? Do you not load additional items at all and just load all at once? Thank you

**Comment by fredericojesus** [comment]
@mhumeniuk I did load a lot a once not all just to check if the bugs only happened after loading more. And I came to a conclusion that yes, most of the bugs only happen after loading more items but in my case I can't load all items at once, they are too much.
Since I don't have a solution here in the library yet, me and my team will probably implement our own version of infinite scrolling.

**Comment by kpaxton** [comment]
Would love it this was merged and released. I need this.

**Comment by vjonas** [comment]
any updates on how to use it when rows have different heights?

**Comment by kykint** [comment]
@rintoj  Could you finally merge this feature?

**Comment by kykint** [comment]
https://www.npmjs.com/package/ngx-virtual-scroll-plus

**Comment by sam-lex** [comment]
@kykint commenting here since there's no issue tracking in your fork.  
`.scrollInto` is not working when there are items of different height. other than that, is working well (single column)

**Comment by UserGalileo** [comment]
@kykint Awesome, the only problem I see is that everything is working fine when I'm scrolling with the mouse but if I scroll down with the scrollbar and I go back up, I lose the first elements. Could you see if you can try it and fix it? :)

**Comment by kykint** [comment]
@UserGalileo I will check , but on my project with big amount of elements with different heights it works fine.

**Comment by UserGalileo** [comment]
@kykint In the meantime I solved it by setting a higher number of buffered elements, I'll see in the next days, if the problem persists I'll make a demo in order to show the problem :)

**Comment by UserGalileo** [comment]
@kykint I'm working on it and I warn you that these lines are making the change event not working when scrolling up:

```
if (this.startupLoop === true || (this.previousChildHeight && this.previousScrollNumberElements)) {
  this.refresh();
} else {
  this.change.emit({start, end});
}
```

The second condition of the if statement is the problem, I removed it and it seems to work :)

**Comment by kykint** [comment]
Hm. It's working fine with sctolling up, without any changes

**Comment by UserGalileo** [comment]
@kykint Who knows, I had that error with your fork, tried with the original one and it worked, checked the diff and found that that line was causing the problem. I guess there are a lot of things that could cause those issues that maybe in your examples don't appear!

I made a really simple example for you, based on one of the examples in the docs. Try to scroll down and then scroll up again, the change event isn't emitted correctly, just sometimes it does (look at the top where it says which elements are showing up)

[https://stackblitz.com/edit/ngx-virtual-not-working](https://stackblitz.com/edit/ngx-virtual-not-working)

**Comment by speige** [comment]
Since this PR is out of date with kykint/master, I've replaced it with https://github.com/rintoj/angular2-virtual-scroll/pull/206

**Comment by speige** [comment]
I merged this PR, but wasn't happy with the results (maybe I did something wrong?). Anyways, I re-coded it and came up with something that seems to work better. It's committed, has a demo, & is available in NPM (behind a flag which is documented in the readme). Could someone test it & give feedback?

**Pull request closed without merging**
