### PR TITLE
Add support for not equals elements

### PR DESCRIPTION
**Pull request by kykint**

### CODE REVIEW

**Comment by speige** [comment]
@kykint Thanks for submitting this. I'd like to see a demo of the bug this fixes before merging. 

http://rintoj.github.io/angular2-virtual-scroll/samples has a button for "toggle random height". Does this demo reproduce the issue? If not, a code sample or stackblitz would be great.

Thanks!

**Comment by kykint** [comment]
The scrolling is very jerky. Look at the video: https://yadi.sk/i/J8TX70Ka3aEtgvIf the elements have very different sizes (100px and 500px) it will be much more awful. This MR solves this issue.

**Comment by speige** [comment]
I did a quick test against the demo using "toggle random heights" with heights 100-500px & scrolling using the PR's code is significantly smoother!

I will definitely merge this. Just give me some time to test that there are no un-intended side effects/bugs & also to do a code review to see if there's any cleanup/optimizations needed.

Thanks!

**Comment by kykint** [comment]
Ok. In fact for `enableUnequalChildrenSizes === false` nothing is changed in logic.

**Comment by speige** [comment]
I've merged your PR & published to npm.

Thanks so much for your help!

I refactored your code a bit. Hope you don't mind. If you have any concerns about anything I changed, please let me know so I can correct it.

Would you mind testing to ensure it's working how you expect?

One breaking change I made that I'm wondering if you agree with:
Since getClientRect only works on visible items, any items that haven't been scrolled are unknown. This makes some of the calculations "estimates". The old code used the minimum child size as the "estimated" value. I'm now using the average child size. (The average itself is an estimate, so it should become more accurate with time)

With the old code if you quickly dragged the scrollbar "thumb" the viewport was smooth, but the "thumb" was jumpy. This is because the invisible total-padding height was changing dynamically as they scrolled. This will still happen with average, but it should be a bit smoother.

Thoughts?

Also, fyi, I noticed scrollToIndex wasn't working well because it calculated the final scroll value 1x, but the "estimates" would change during the scroll animation causing the pre-calculated value to be incorrect. I modified the function to retry a few times until the calculations stabilize.

**Pull request merged**
