### PR TITLE
chore: update to angular 10

### LINKED ISSUE #457: Support for Angular v10
When using the project with Angular 10, I get the following warning:

```
npm WARN ngx-virtual-scroller@4.0.3 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
```

Angular v10 updates tslib to version 2, hence the warning.

### PR DESCRIPTION
**Pull request by Michsior14**
Fixes: #457

### CODE REVIEW

**Review by whyboris — APPROVED** [review]
Amazing work! 

And thank you for all the formatting cleanup & standardization and the numerous small fixes (like prepending `app-` to components as Angular standards recommend 😍

**Comment by whyboris** [comment]
@speige -- while I have repository rights to merge the commit, I would feel safer if you glance over it and do it 🤝 

I think this is an excellent change and I look forward to it getting merged 🙌

**Comment by ahnpnl** [comment]
hi, are there any updates on this ?

**Comment by SvenBudak** [comment]
@rintoj if this package fix some problems, maybe accept the merg reuqest? :) 
We have currently problems to make this package work in latest angular version... a fix would be great

**Comment by whyboris** [comment]
@speige or @vanackere -- as far as I can tell this is a great PR that is safe to merge; please confirm if you have time and merge 🙇

**Review by vanackere — APPROVED** [review]
Looks good

**Comment by vanackere** [comment]
@whyboris fine with me to merge this... (but I'm not sure who can publish a new release on npm even once this is merged if the original maintainer is missing...)

**Comment by SvenBudak** [comment]
@vanackere What is with rintoj? he cant publish anymore packages on npm?

**Comment by vanackere** [comment]
@Michsior14  could you please rebase your branch and resolve the conflicts in demo/package-lock.json ?

**Comment by vanackere** [comment]
> @vanackere What is with rintoj? he cant publish anymore packages on npm?

@SvenBudak : all I meant is that if @rintoj is not available to merge this pull request, he probably doesn't have time either to push a new release on npm...

**Comment by SvenBudak** [comment]
I work with a friend on a open source lib. its in early progress. here is the first documentation entry: https://devmonkeysde.gitbook.io/mark6/components/image

We plan to use ngx-virtual-scroller for our messenger. but we have a huge problem: https://imgur.com/ShYjIJj It seems that the scroller cant handle the dynamic heights of the items. Here in live: https://mark6-demo.web.app/messenger (Please check it in Device Emulator in chrome for example, with smartphone.)

If @rintoj is okay with this idea, can we maybe add ngx-virtual-scroller to mark6? just an idea :)

**Comment by Sampath-Lokuge** [comment]
Can we have this release soon? i.e Angular 10 support?

**Comment by Sampath-Lokuge** [comment]
Hi, @speige Any feedback about this release?

**Comment by whyboris** [comment]
@rintoj -- this seems like a great PR, do you have a comment on this? 😊

**Comment by tiagodev** [comment]
the last release was almost a year ago... is this project dead?

**Comment by SvenBudak** [comment]
@tiagodev There is one thing i learned in last years.. never try to use any virtual scroll lib. they are NEVER working. just try to solve your apps without it.

**Comment by whyboris** [comment]
@tiagodev - this project is not dead, it works perfectly well. Just because it's not updated with the latest version of everything, doesn't mean it's not worth using.

@SvenBudak please reflect on your comment. This is a [production-ready](https://github.com/whyboris/Video-Hub-App/blob/main/package.json#L51) project that is used in free and commercial applications. I'm sorry to hear you have had trouble with libraries. But given that there are close to 1,000 stars on this repository (with thousands of users successfully implementing this library), your advice seems inappropriate. Please consider how rude it would be to be standing next to someone who freely is sharing their work to help others, and to just say an equivalent of what you just said. Are you actively trying to discourage people from building things with intention of helping others?

**Comment by tiagodev** [comment]
@whyboris glad to hear that. I've been using it for a long time already and I was just wondering why the long wait since there's activity around here.

**Comment by SergioGMB** [comment]
I'm sorry to tag you, but someone can merge and release this? @whyboris 
Thanks a lot!

**Comment by whyboris** [comment]
I have the repository rights to _merge_ but I don't have the ability to craft the `npm` release.
@rintoj -- would you be willing to create a new release if this gets merged? If so, I will do a thorough pass on the PR before merging 👌

**Comment by ggallotti** [comment]
Any news about this?

**Comment by denniske** [comment]
@whyboris @speige If you have the time, I suggest creating a new repo ngx-virtual-scroller-next. Do a feature freeze and only update the library to work with the latest angular version. Publish a new npm package ngx-virtual-scroller-next.

This would greatly increase the value of this project and encourage people to use it.

**Comment by nerumo** [comment]
why closed?

**Comment by Michsior14** [comment]
> why closed?

This project looks dead too me and I am not interested in keeping it up to date nor implement any feedback.

**Comment by Sampath-Lokuge** [comment]
Try this and compatible with the latest Angular: https://github.com/lVlyke/lithium-ngx-virtual-scroll

**Comment by nerumo** [comment]
> Try this and compatible with the latest Angular: https://github.com/lVlyke/lithium-ngx-virtual-scroll

wow, thank you

**Comment by rooby** [comment]
Here is a fork of ngx-virtual-scroller that has a reasonable amount of users:
https://www.npmjs.com/package/@iharbeck/ngx-virtual-scroller

**Comment by nerumo** [comment]
> Here is a fork of ngx-virtual-scroller that has a reasonable amount of users:
> https://www.npmjs.com/package/@iharbeck/ngx-virtual-scroller
> 

I know, but there are new performance features (async rendering and caching) that I missed

**Comment by ichepurnoy** [comment]
> > why closed?
> 
> This project looks dead too me and I am not interested in keeping it up to date nor implement any feedback.

@Michsior14  There is an +/- actively maintained fork, updated for Angular 16 [https://www.npmjs.com/package/@iharbeck/ngx-virtual-scroller](https://www.npmjs.com/package/@iharbeck/ngx-virtual-scroller) . Could you please consider making a PR to that repo?  Thank you for your efforts!

**Pull request closed without merging**
