### PR TITLE
Fix incorrect placement of element below virtual-scroll

### PR DESCRIPTION
**Pull request by adrianmuzychenko**
FIx for issue https://github.com/rintoj/ngx-virtual-scroller/issues/429

### CODE REVIEW

**Comment by azerafati** [comment]
I checked this for my use case and it works by adding enough space for footer to move to the end of scroll, but it does break virtual-scroll as it it no longer removes items out of view from DOM at least for me, I'll try to add an stackblitz later to show this

**Review by azerafati — COMMENTED** [review]
I checked this for my use case and it works by adding enough space for footer to move to the end of scroll, but it does break virtual-scroll as it it no longer removes items out of view from DOM at least for me, I'll try to add an stackblitz later to show this

**Comment by scote** [comment]
Will it be merged soon?

**Comment by Smip** [comment]
@adrianmuzychenko why did you close PR?

**Pull request closed without merging**
