### PR TITLE
Added optional input to consider padding area.

### PR DESCRIPTION
**Pull request by thomazcapra**
I had the following problem:

When the scrollable-content is configurate with padding, in some point after scroll all items disapear.

To fix this problem, I had to add a new input property to allow us to consider padding dimensions as scrollable width.

### CODE REVIEW

**Comment by thomazcapra** [comment]
@rintoj please, let me know if this change can be made, regards!

**Comment by speige** [comment]
@thomazcapra It looks like this was closed without ever being merged. I'm really sorry about that. Are you still interested in working on this? If so, would you mind re-basing your changes off the head of master to get rid of all the merge conflicts? Thanks.

**Comment by speige** [comment]
The code has changed a lot since this PR was first created. I'm curious whether the padding bug has already been fixed by something else. Let's test the newest version to see if it still has an issue before we merge this PR.

**Comment by speige** [comment]
I think a better solution might be this:

```
.scrollable-content * {
    box-sizing: border-box;
}
```

**Comment by speige** [comment]
I've decided to do the box-sizing: border-box css change. This is now committed to github, but not yet released to npm. I believe that resolves this PR, so I'm closing it. Please re-open if you disagree.

**Pull request closed without merging**
